### ISSUE TITLE
Deploy the kandy web-app on server

### ISSUE THREAD

**Issue by kamalhakim** [karamelchef/kandy#1]
Sub-tasks:
 1. Configure the Snurran machine, install Payara and create kandy-database on mysql
 2. Write a bash script for kandy to build, package and auto-deploy the war-file on the server
 3. Make sure to have right jpa update-policy on kandy for new db shcemas

**Comment by mhsina** [comment]
deployed.
Deployment process is throw netbeans.

**Comment by kamalhakim** [comment]
Close!!
