### ISSUE TITLE
Design and implement a REST-API for collecting karamel statistics 

### ISSUE THREAD

**Issue by kamalhakim** [karamelchef/kandy#2]
You should handle it in rest-layer and database.

**Comment by mhsina** [comment]
Parameters to be supplied by the karamel client
1. Execution ID (Contains cluster name)
2. User ID
3. client Ip address 
4. Recipe ID
5. VM Type (pointer to VM table)
6. Time

**Comment by mhsina** [comment]
Implemented and deployed

**Comment by kamalhakim** [comment]
Close the issue when you are done!!
